ページング処理を追加
ysknsid25/booby pull request #15
Opened 2023-06-03 08:19 UTC by george0528

## 関連チケット
#6 

## 概要
- クエリパラムに応じたページング処理を追加
- Paginationコンポーネントをフロントエンドに追加
- バックエンドでページに応じたapi通信に変更

## 動作確認方法
どのような動作確認が必要か書いてください。
- Paginationのtestコードを追加

## フロントエンド
<img width="521" alt="image" src="https://github.com/ysknsid25/booby/assets/79493776/0cf10774-8989-4716-a166-b1b35d21b708">

## 気になっているところ/補足
自信のないところや特にレビューしてほしいところ、その他補足したいことがあれば記載してください。

2023-06-09 15:11 UTC, george0528 commented
UIの仕様がそもそもおかしかったので修正します。

2023-06-09 15:53 UTC, george0528 commented
修正しました

2023-06-10 03:18 UTC, ysknsid25 reviewed
反応が遅くなり申し訳ありません🙇
いくつかコメントしましたので、確認をお願いいたします🙏

2023-06-10 03:18 UTC, ysknsid25 commented on src/pages/api/githubApi.ts
>      per_page: 50,
1ページあたりの表示件数を意味する50が至る所にハードコードされていますが、searchConditionに持たせることでハードコードを回避できませんか？🤔

あと、1ページあたりの表示件数はユーザーが変えられてもいいと考えています。
今すぐに対応する必要はありませんが、searchConditionに持っていればそのような改修が発生した場合にも変更箇所が少なく済むという恩恵を得られそうです。

2023-06-10 03:18 UTC, ysknsid25 commented on src/pages/index.tsx
> +    // language
下のif文の判定を見れば明らかなので、このコメントはいらないです🙏

2023-06-10 03:18 UTC, ysknsid25 commented on src/pages/index.tsx
> +    // sort
同上

2023-06-10 03:18 UTC, ysknsid25 commented on src/pages/index.tsx
> +    // page
同上

2023-06-10 03:18 UTC, ysknsid25 commented on src/Components/pagination.tsx
> +  if (totalCount > 1000) {
説明変数を作ってください。
コメントが添えられているだけマシですが、マジックナンバーは徹底的に排除してください。
(1行だけの短命であればよいですが下の40行目でも再利用しているということは、いずれどこかで再利用される可能性が高いため)

```suggestion
// 1000件以上はAPI制限でエラーになるため、1000件までの遷移先しか表示しない
const apiMaxCount = 1000
  if (totalCount > apiMaxCount) {
```

あと細かいですが、コメントだと1000件目もエラーになりそうなものですが、
・totalCount >= 1000かつ1000件以上はAPI制限でエラーになるため、999件までの遷移先しか表示しない
・totalCount >1000かつ1001件以上はAPI制限でエラーになるため、1000件までの遷移先しか表示しない
のどちらが正しいですか？
(のように誤解を生むもとになるので、私は説明変数が好きです。コードが全てなので。)

2023-06-10 03:18 UTC, ysknsid25 commented on src/Components/pagination.tsx
> +function getPageNumbers(currentPage: number, totalPage: number): Array<string | number> {
コードから明白ですが、一応関数コメントをつけておいてください🙏

2023-06-10 03:18 UTC, ysknsid25 commented on src/Components/__test__/pagination.test.tsx
> +  })
`ページ数が7以上の場合`のテストで、`currentPage `が`urrentPage <= 3`以外の2パターンについても網羅しておいてください🙏

```suggestion
//例
test('Paginationのページ数が7以上の場合かつ現在ページが4のときに左右に「...」が表示されているかどうか', () => {
//テスト
})
test('Paginationのページ数が7以上の場合かつ現在ページが4のときにlinkの数が5つ表示されているかどうか', () => {
//テスト
})
test('Paginationのページ数が7以上の場合かつ現在ページが最終ページの2ページ前のときに左に「...」が表示されているかどうか', () => {
//テスト
})
test('Paginationのページ数が7以上の場合かつ現在ページが最終ページの2ページ前のときにlinkの数が5つ表示されているかどうか', () => {
//テスト
})
```

2023-06-10 03:24 UTC, ysknsid25 commented
あと細かいですが、あとから確認する人のためにプルリクのコメントを修正しておいてください。

>ページネーションのパターンは3種類あります。

4種類ですよね？(6ページ目以下のパターンがあるので)

2023-06-12 08:11 UTC, george0528 commented on src/Components/pagination.tsx
> +  if (totalCount > 1000) {
誤解を生む書き方をしてしまい申し訳ありません🙇
正しくは
- totalCount >1000かつ1001件以上はAPI制限でエラーになるため、1000件までの遷移先しか表示しない

です

2023-06-15 16:54 UTC, george0528 commented
@ysknsid25 
丁寧なコードレビューありがとうございました🙇‍♂️
コメントにあった分は修正しました🔧
他に気になる点がございましたら、お手数をおかけしますが教えて頂けますと幸いです🙏

2023-06-16 00:27 UTC, ysknsid25 requested changes
1点だけ再度確認をお願いいたします🙏

2023-06-16 00:27 UTC, ysknsid25 commented on src/Components/pagination.tsx
> +  const apiMaxCount = 1000
コメントがおかしいままなので、説明変数を作ったのであればコメントは削除してしまってください🙏

2023-06-16 12:37 UTC, george0528 commented on src/Components/pagination.tsx
> +  const apiMaxCount = 1000
@ysknsid25 
修正いたしました!

2023-06-18 01:35 UTC, ysknsid25 approved these changes
修正対応ありがとうございました。
LGTMです👍

2023-06-18 01:35 UTC, merged